### ISSUE TITLE
reference working repo in published draft

### ISSUE THREAD

**Issue by vttale** [fcelda/nsec5-draft#10]
Just a thought to do with as the group wants.  At the start of another draft my co-author and I have:

 [ Ed note: Text inside square brackets ([]) is additional background
   information, answers to frequently asked questions, general musings,
   etc.  They will be removed before publication.  This document is
   being collaborated on in Github at: https://github.com/[...].
   The most recent version of the document, open issues, etc  should all 
   be available here.  The authors (gratefully) accept pull requests ]

I think we should have something like that on this one too.

**Comment by goldbe** [comment]
i think its a good idea, added it.
