### ISSUE TITLE
once vrf draft is submitted, edit nsec5 draft to link to it properly 

### ISSUE THREAD

**Issue by goldbe** [fcelda/nsec5-draft#13]
Also section 4 of the nsec5 id  should reference specific sections of the vrf id, make sure to fix that.

**Comment by vttale** [comment]
I'd updated the general ref a couple of days ago but we still need to fix the one Sharon called out for a specific section reference.

**Comment by goldbe** [comment]
I've updated Section 5 of NSEC5. I consider this closed for now.
See c013e1c8e93e9e39585e540cd94035731c4e08c1.
