### ISSUE TITLE
Leo wants to hash the PK as input to ECVRF_hash_to_curve  and in MGF1 for the RSA-FDH-VRF

### ISSUE THREAD

**Issue by goldbe** [fcelda/nsec5-draft#14]
"otherwise you get into weird issues with the RO proof of pseudorandomness not composing for multiple copies of the same VRF with different PKs, because you have to program the RO in different ways that may contradict each other. Generally, hashing PK is good hygiene -- like salting hashes. Aside from proof issues, it simply makes attacker's job harder because you have to attack per PK, and precompute some crazy table once and for all."

**Comment by goldbe** [comment]
Added this as a comment to VRF draft but did not actually implement the change. Waiting for someone else to do this so I don't screw up any EC point to octet conversion.

**Comment by goldbe** [comment]
Here is the commit: https://github.com/fcelda/nsec5-draft/commit/d77815bc11d20620de412d134c6c657a35c0d777

**Comment by fcelda** [comment]
Fixed in 455440a304457df6a5b3a64ca4bb1cf75621b57a
