### ISSUE TITLE
vrf draft hash-to-curve when sizes don't match

### ISSUE THREAD

**Issue by reyzin** [fcelda/nsec5-draft#15]
In section 5.4.1.1 of the vrf draft, OS2ECP will reject if Hash(alpha || pk || CTR) is not in the correct finite field. For prime fields, this means reject if Hash(alpha || pk || CTR)>= the prime over which the curve is defined (this prime has no name in the draft; it is not the same as the curve order q, but it is close to q; it is usually called p). Similarly, for fields of characteristic 2, OS2ECP will reject if Hash(alpha || pk || CTR) has a 1 in any position that extends beyond the field size. This rejection will happen because of http://www.secg.org/sec1-v2.pdf Section 2.3.6, invoked via Section 2.3.4 step 2.2. 

The field size can differ from hash size by up to 7 bits in the draft, causing average number of trials to avoid this rejection to be as high as 128 (this is before we even get to the "is this point on the curve" part of OS2ECP, which itself has probability 1/2 of rejection). To avoid this, I propose to zero out the correct number of leading bits of Hash(alpha || pk || CTR), so that the average number of trials to get x smaller than the prime is at most 2. This proposal requires no changes in the most common case, when the prime and the hash function have the same bit length (e.g., 256, as in P256 or Curve25519).

**Comment by fcelda** [comment]
Nice catch. So how we are gonna write this down? I'm not sure how to express the bit length of the curve as I failed to find it in SEC1 which we use to refer to for EC definitions. In [Section 5](https://tools.ietf.org/html/draft-goldbe-vrf-00#section-5) of the draft, we already have `2n = ceil(log2(q)/8)` which tells something similar. But I'm not sure if we are happy with this formula. Anyway, the number of high bits to clear in Hash output should be `hLen - ceil(log2(q))`. Right? Does it make sense?

Another options is to keep this up to the particular instantiation of EC VRF. We just provide Hash to be a fixed parameter in the general definition. The instantiation then says what Hash is. So for example with [EC-VRF-P256-SHA256](https://tools.ietf.org/html/draft-goldbe-vrf-00#section-5.5), Hash is said to be SHA-256. If someone wants a different instantiation with a curve that has a length less than 256 bits, Hash can be defined as "truncated" SHA-256.

**Comment by goldbe** [comment]
Jan: the second option is not a good idea, because one could choose a hash that is too short, and then the VRF is not secure (to the same bit level as the curve). For instance, you could have a 384-bit curve but then someone could decide to use the SHA-256 hash. Not good.

**Comment by fcelda** [comment]
I agree. So the first option it is. Are you comfortable with me updating the draft using the syntax I've used?

**Comment by reyzin** [comment]
Jan, you wrote: "Anyway, the number of high bits to clear in Hash output should be hLen - ceil(log2(q))." Note quite, because it's not q, but the size of the field over which the curve is defined. If you don't mind, I will try to update the draft, since I've already spent some time thinking how to do it.

**Comment by fcelda** [comment]
Sure. Go ahead.

**Comment by goldbe** [comment]
So, after discussion with Leo we decide that all the curves we specify now (or ever will specify ie P256, Ed25519, Ed448) are over finite fields F where the bitlength of field elements in F are divisible by 16.    This made things easier because we now don't need to clear anything in the hash output.  So I made this change in https://github.com/fcelda/nsec5-draft/commit/5ceb74d49c1f189e2b17734fbd138754d8dd17a2
which also specifies that the output length of Hash is 2n octets, which is also the octet length of field elements in F.

**Comment by fcelda** [comment]
Looks good.
