### ISSUE TITLE
"Constraints on options" text in VRF draft

### ISSUE THREAD

**Issue by reyzin** [fcelda/nsec5-draft#17]
We have text "Cryptographic security of Hash is at least as high as the cryptographic security level of the RSA key" and "Cryptographic security of Hash is at least as high as the cryptographic security of G". This is not clear: what do we mean by "cryptographic security"? How do you evaluate it? And what if the RSA key or G hash slightly higher security -- is that now completely ruled out?

Not sure what we should do about this.

**Comment by goldbe** [comment]
Got rid of it. This is ok since we say that the hash function output length must be 2n.
