### ISSUE TITLE
ECVRF_hash_to_curve1 not usable when input must be kept secret?

### ISSUE THREAD

**Issue by reyzin** [fcelda/nsec5-draft#18]
The draft says "this algorithm MUST NOT be used in applications where the VRF input alpha must be kept secret" because of possible timing attacks. However, timing attacks may be not possible in some settings, may be mitigated in others, and anyway, as the draft itself says, the leakage is very small (expected 1 bit). Does MUST NOT really belong there?

**Comment by goldbe** [comment]
You're right. We could say SHOULD NOT.

**Comment by goldbe** [comment]
Or, we could put in a sentence like the one you wrote above.

**Comment by goldbe** [comment]
Made this change in https://github.com/fcelda/nsec5-draft/commit/1a0bc30bf292fe769f2e34002fbf2c1c50da5525
