### ISSUE TITLE
ECVRF verifying if curve has cofactor > 1

### ISSUE THREAD

**Issue by reyzin** [fcelda/nsec5-draft#19]
Verifying says to fail "If gamma is not a valid EC point in G" but doesn't specify how to check if gamma in G (ECVRF_decode_proof will only check if gamma is on the curve, which is a superset of G if cofactor > 1). The VRF is NOT secure without such a check (specifically, uniqueness can be violated if gamma is a valid EC point but not in G -- more than one gamma could be valid). I see two choices:

- We could specify that, if cofactor > 1, verifying should check if gamma^q = O (point at infinity). That will make sure that gamma is in G. However, it has a cost of a full EC operation.

- We could instead take the approach of https://whispersystems.org/docs/specifications/xeddsa/#vxeddsa , which does not verify if gamma is in G, but rather computes gamma^cofactor as the first step of ECVRF_proof2hash. We would need to add to our proof to show that gamma^cofactor is unique even if gamma is not in G.

**Comment by goldbe** [comment]
Leo and I just talked, and it looks like the second solution makes more sense. Currently we think this means that VRF_proof2hash needs to be modified as follows.

VRF_proof2hash (gamma)
     gammaPrime = gamma^cofactor
     take the x coordinate of gammaPrime

**Comment by goldbe** [comment]
We decided to take the second solution and I've implemented it in https://github.com/fcelda/nsec5-draft/commit/f277c06f26ec579dcaaf480700b7bd56f3d75ce8
