### ISSUE TITLE
VRF terminology

### ISSUE THREAD

**Issue by fcelda** [fcelda/nsec5-draft#26]
Do you feel like the Terminology needs to be extended?

I noticed that we often use _VRF prover that holds VRF SK_ for instance. Maybe we could shorten this just into _Prover_ in case we define this as a term.

Just an idea. I don't have strong opinion on that.

**Comment by goldbe** [comment]
I like it.  If you want to go ahead and add it, you can. Else I will when I next take a pass on the draft.

**Comment by goldbe** [comment]
Made this change. Also added "Verifier".
See commit 404c6e0fff1101706f62de6a1b15a05eda172b34
