### ISSUE TITLE
OS2ECP failed state

### ISSUE THREAD

**Issue by fcelda** [fcelda/nsec5-draft#27]
@goldbe ad your removed cref in pull #24.

I checked that the OS2ECP algorithm has a variant of a failed state:

- [SEC 1](http://www.secg.org/sec1-v2.pdf) section 2.3.4 for NIST P256 outputs "invalid".
- [RFC 8032 Secion 5.1.3](https://tools.ietf.org/html/rfc8032#section-5.1.3) for Ed25519 says that "decoding fails" instead of explicitly giving "invalid" as an output.

Do you think it has to be clarified? RFC8032 uses less formal and more descriptive language.

**Comment by goldbe** [comment]
No, I think it is fine.  I just wanted to make sure that you checked.  Thank you.
