### ISSUE TITLE
Suite names in test vectors don't match the specification

### ISSUE THREAD

**Issue by fcelda** [fcelda/nsec5-draft#36]
There are some inconsistencies in naming the cipher suites.

`ECVRF-EDWARDS25519-SHA512-ELL2` vs `ECVRF-ED25519-SHA512-Elligator2` and a few others.

**Comment by reyzin** [comment]
Resolved by https://github.com/fcelda/nsec5-draft/commit/ee718d9362bcf4e022667bf28b9bd54ba4351a4b
